# Clean dataset

### Load OECD-Dataset into a CSV

In [2]:
import pandas as pd 

df = pd.read_csv("../../data/OECD-Dataset.csv")
df.head()

/var/folders/sp/zrg_wt6n4hs4l4nz5y1b6zs00000gn/T/ipykernel_41251/1717978331.py:3: DtypeWarning: Columns (0: year, 1: grant_recipient_project_title, 2: expected_duration, 3: financial_instrument, 4: modality_of_giving, 5: gender_dimension, 6: additional_info, 7: subsector, 8: Sector, 9: channel_name, 10: channel_reported_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/OECD-Dataset.csv")

,year,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
0,2021,Lund Trust,South & Central Asia,Afghanistan,0.007338,For Afghanistan,To support Turquoise Mountain's work in Afghan...,NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia
1,2021,Lund Trust,Eastern Africa,Kenya,0.008166,Vanga Blue Forest,Towards mangrove conservation in southern Kenya,NaN,Cross-border,United Kingdom,...,General Environment Protection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa
2,2022,Lund Trust,Europe,Ukraine,6.795787,"To the crisis appeal, to support the people of...","To the crisis appeal, to support the people of...",NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
3,2022,Lund Trust,Europe,Ukraine,0.339789,Match funding for the Refugee Council's appeal,"To develop, expand and run the services needed...",NaN,Cross-border,United Kingdom,...,Refugees in Donor Countries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
4,2022,Lund Trust,Europe,Ukraine,4.077472,To support the emergency response in Ukraine.,To support the emergency response in Ukraine.,NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe

### Clean years
Some years are strings and others are integers, turn them all to integers.

In [3]:
df.groupby('year').count()

,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,financial_instrument,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
year,,,,,,,,,,,,,,,,,,,,,
2020,34121,34121,34121,33941,21845,32132,6524,34121,34121,16485,...,33232,11950,14961,14955,14965,4579,14850,4546,3532,34121
2021,26868,26868,26868,26360,23027,24469,6730,26868,26868,16966,...,25816,10138,14917,14907,14912,4993,12881,4943,4457,26868
2022,28679,28679,28679,28426,23585,25915,7952,28679,28679,16769,...,27561,10452,15045,15038,15040,5341,13131,5340,5126,28679
2023,25020,25020,25020,24846,15736,22169,7672,25020,25020,16106,...,23972,11453,14559,14542,14559,6333,12088,6668,6215,25020
2020,482,482,482,479,399,83,387,482,482,0,...,482,0,0,0,0,0,0,0,0,482
2020-2023,3,3,3,3,0,0,0,3,3,3,...,3,0,0,0,0,0,0,0,0,3
2021,422,422,422,420,422,0,393,422,422,0,...,422,0,0,0,0,0,0,0,0,422
2022,445,445,445,442,431,14,408,445,445,0,...,445,0,0,0,0,0,0,0,0,445
2023,521,521,521,521,520,1,479,521,521,0,...,521,0,0,0,0,0,0,0,0,521

In [4]:
df_2020_23 = df[df['year'] == '2020-2023']
df_2020_23

,year,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
116558,2020-2023,Cartier,Far East Asia; Southern Africa; GLOBAL or unsp...,"Cambodia; South Africa; Developing countries, ...",67.016705,NaN,NaN,NaN,Cross-border,France,...,"Water Supply & Sanitation; Agriculture, Forest...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia; Africa; GLOBAL or unspecified; Middle Ea...
116559,2020-2023,Fondation De Luxembourg,Eastern Africa; Southern Africa; Western Afric...,Madagascar; South Africa; Senegal; Thailand; C...,12.201227,NaN,NaN,NaN,Cross-border,Luxembourg,...,Government & Civil Society; Education; Other M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa; Asia; America; Middle East; Europe
116560,2020-2023,Sabanci,Europe,Türkiye,6.339514,NaN,NaN,NaN,Domestic,Turkey,...,Government & Civil Society; Health; Other Soci...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe

Handle ranges of 2020-2023: Split into 2020, 2021, 2022, and 2023 with funding evenly distributed across 4 years.

In [5]:
def handle_range(row):
    if (row['year'] == '2020-2023'):
        row['year'] = [2020, 2021, 2022, 2023]
        row['usd_disbursements_defl'] = row['usd_disbursements_defl'] / 4
    elif (type(row['year']) is str):
        row['year'] = int(row['year'])
    return row

df = df.apply(handle_range, axis=1)
df = df.explode('year')
df.head()

,year,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
0,2021,Lund Trust,South & Central Asia,Afghanistan,0.007338,For Afghanistan,To support Turquoise Mountain's work in Afghan...,NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia
1,2021,Lund Trust,Eastern Africa,Kenya,0.008166,Vanga Blue Forest,Towards mangrove conservation in southern Kenya,NaN,Cross-border,United Kingdom,...,General Environment Protection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa
2,2022,Lund Trust,Europe,Ukraine,6.795787,"To the crisis appeal, to support the people of...","To the crisis appeal, to support the people of...",NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
3,2022,Lund Trust,Europe,Ukraine,0.339789,Match funding for the Refugee Council's appeal,"To develop, expand and run the services needed...",NaN,Cross-border,United Kingdom,...,Refugees in Donor Countries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
4,2022,Lund Trust,Europe,Ukraine,4.077472,To support the emergency response in Ukraine.,To support the emergency response in Ukraine.,NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe

In [6]:
df.groupby('year').count()

,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,financial_instrument,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
year,,,,,,,,,,,,,,,,,,,,,
2020,34606,34606,34606,34423,22244,32215,6911,34606,34606,16488,...,33717,11950,14961,14955,14965,4579,14850,4546,3532,34606
2021,27293,27293,27293,26783,23449,24469,7123,27293,27293,16969,...,26241,10138,14917,14907,14912,4993,12881,4943,4457,27293
2022,29127,29127,29127,28871,24016,25929,8360,29127,29127,16772,...,28009,10452,15045,15038,15040,5341,13131,5340,5126,29127
2023,25544,25544,25544,25370,16256,22170,8151,25544,25544,16109,...,24496,11453,14559,14542,14559,6333,12088,6668,6215,25544

### Explore organization_name, region, country, grant recipient

In [7]:
df.groupby('organization_name').count()

,year,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,financial_instrument,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
organization_name,,,,,,,,,,,,,,,,,,,,,
Accion Cultural Y Social De Monterrey,28,28,28,28,0,28,0,28,28,0,...,28,0,0,0,0,0,0,0,0,28
Adani Enterprises,38,38,38,38,38,0,0,38,38,0,...,25,0,0,0,0,0,0,0,0,38
Adani Ports And Special Economic Zone Limited,52,52,52,52,52,0,0,52,52,0,...,44,0,0,0,0,0,0,0,0,52
Aditya Birla Finance,60,60,60,60,60,0,0,60,60,0,...,45,0,0,0,0,0,0,0,0,60
Adobe Home Aid,35,35,35,35,0,35,0,35,35,0,...,35,0,0,0,0,0,0,0,0,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zhejiang Xinhu Charity Foundation,47,47,47,47,47,22,0,47,47,0,...,40,0,0,0,0,0,0,0,0,47
Zhejiang Xizi Charity Foundation,30,30,30,30,30,30,0,30,30,0,...,27,0,0,0,0,0,0,0,0,30
Zhongtian Love Charity Foundation,33,33,33,33,33,33,0,33,33,0,...,29,0,0,0,0,0,0,0,0,33
Zhuhai Huafa Charity Foundation,109,109,109,109,109,109,0,109,109,0,...,91,0,0,0,0,0,0,0,0,109
Zijin Mining Charity Foundation,45,45,45,45,45,45,0,45,45,0,...,35,0,0,0,0,0,0,0,0,45

In [8]:
df.groupby('region').count()

,year,organization_name,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,financial_instrument,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
region,,,,,,,,,,,,,,,,,,,,,
Africa,2576,2576,2576,2538,2280,2554,1060,2576,2576,2576,...,2565,1884,2472,2469,2473,956,2044,956,880,2576
America,1007,1007,1007,1003,997,1007,33,1007,1007,1007,...,1007,968,1006,1006,1006,33,419,32,31,1007
Asia,816,816,816,803,740,808,242,816,816,816,...,815,652,813,810,813,239,615,239,218,816
Caribbean,464,464,464,454,452,464,128,464,464,437,...,451,257,349,349,349,35,301,38,33,464
Caribbean & Central America,127,127,127,124,100,127,94,127,127,127,...,127,76,125,123,125,92,125,92,85,127
Central America,29487,29487,29487,29417,5745,27706,3141,29487,29487,2280,...,29387,1614,2080,2080,2078,76,1940,94,71,29487
Eastern Africa,11003,11003,11003,10825,9795,10913,5285,11003,11003,9913,...,10684,6423,9335,9333,9335,3743,8751,3779,3424,11003
Eastern Africa; Southern Africa; Western Africa; Far East Asia; Middle Africa; South & Central Asia; South America; Central America; North of Sahara; Middle East; Caribbean; Europe; Africa,4,4,4,4,0,0,0,4,4,4,...,4,0,0,0,0,0,0,0,0,4
Europe,1506,1506,1506,1498,1493,1442,272,1506,1506,1287,...,1473,1000,1158,1158,1157,26,715,39,25,1506
Far East Asia,14779,14779,14779,14683,14558,14675,1108,14779,14779,3347,...,13379,2370,3153,3145,3153,771,3021,801,723,14779
Far East Asia; Southern Africa; GLOBAL or unspecified; Middle East; Western Africa; South & Central Asia; Eastern Africa; Africa; North of Sahara; Caribbean; South America; Europe; Middle Africa; Central America,4,4,4,4,0,0,0,4,4,4,...,4,0,0,0,0,0,0,0,0,4
GLOBAL or unspecified,16394,16394,16394,16201,14621,16279,6298,16394,16394,16368,...,16386,12539,16279,16259,16278,6067,13866,6095,5415,16394
Melanesia,45,45,45,45,42,45,26,45,45,33,...,44,19,33,33,33,14,31,14,14,45
Micronesia,14,14,14,14,14,14,2,14,14,12,...,14,12,12,12,12,0,12,0,0,14
Middle Africa,1624,1624,1624,1580,1474,1617,585,1624,1624,1564,...,1576,653,924,924,924,458,905,464,435,1624
Middle East,1489,1489,1489,1473,1451,1430,290,1489,1489,1479,...,1469,930,1176,1176,1176,139,972,135,121,1489
North of Sahara,1096,1096,1096,1041,1074,1061,336,1096,1096,1079,...,1078,834,754,754,754,58,639,60,57,1096
Oceania,42,42,42,40,36,42,16,42,42,42,...,42,32,42,42,42,16,41,16,16,42
Polynesia,14,14,14,14,12,14,11,14,14,6,...,14,5,6,6,6,4,6,4,4,14
South & Central Asia,17660,17660,17660,17568,16345,8256,4102,17660,17660,8269,...,15944,4389,6415,6415,6415,3354,6015,3388,3011,17660
South America,4917,4917,4917,4854,4819,4890,1516,4917,4917,4532,...,4667,2736,3231,3230,3230,227,2829,236,223,4917
South of Sahara,1944,1944,1944,1908,1522,1944,1500,1944,1944,1944,...,1928,1055,1890,1889,1888,1446,1819,1444,1304,1944
Southern Africa,2750,2750,2750,2707,2514,2743,1135,2750,2750,2531,...,2680,1701,2181,2181,2181,677,2024,736,657,2750
Western Africa,6808,6808,6808,6649,5881,6752,3365,6808,6808,6681,...,6725,3844,6048,6048,6048,2815,5860,2835,2583,6808

Handle region: split on ; and distribute evenly

In [9]:
def handle_regions(row):
    if (';' in row['region']):
        arr = row['region'].split(';')
        arr_strip = [a.strip() for a in arr]
        row['region'] = arr_strip
        row['usd_disbursements_defl'] = row['usd_disbursements_defl'] / (len(arr_strip))
    else:
        row['region'] = row['region'].strip()
    return row

df = df.apply(handle_regions, axis=1)
df = df.explode('region')
df.groupby('region').count()

,year,organization_name,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,financial_instrument,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
region,,,,,,,,,,,,,,,,,,,,,
Africa,2584,2584,2584,2546,2280,2554,1060,2584,2584,2584,...,2573,1884,2472,2469,2473,956,2044,956,880,2584
America,1007,1007,1007,1003,997,1007,33,1007,1007,1007,...,1007,968,1006,1006,1006,33,419,32,31,1007
Asia,816,816,816,803,740,808,242,816,816,816,...,815,652,813,810,813,239,615,239,218,816
Caribbean,472,472,472,462,452,464,128,472,472,445,...,459,257,349,349,349,35,301,38,33,472
Caribbean & Central America,127,127,127,124,100,127,94,127,127,127,...,127,76,125,123,125,92,125,92,85,127
Central America,29495,29495,29495,29425,5745,27706,3141,29495,29495,2288,...,29395,1614,2080,2080,2078,76,1940,94,71,29495
Eastern Africa,11011,11011,11011,10833,9795,10913,5285,11011,11011,9921,...,10692,6423,9335,9333,9335,3743,8751,3779,3424,11011
Europe,1514,1514,1514,1506,1493,1442,272,1514,1514,1295,...,1481,1000,1158,1158,1157,26,715,39,25,1514
Far East Asia,14787,14787,14787,14691,14558,14675,1108,14787,14787,3355,...,13387,2370,3153,3145,3153,771,3021,801,723,14787
GLOBAL or unspecified,16398,16398,16398,16205,14621,16279,6298,16398,16398,16372,...,16390,12539,16279,16259,16278,6067,13866,6095,5415,16398
Melanesia,45,45,45,45,42,45,26,45,45,33,...,44,19,33,33,33,14,31,14,14,45
Micronesia,14,14,14,14,14,14,2,14,14,12,...,14,12,12,12,12,0,12,0,0,14
Middle Africa,1632,1632,1632,1588,1474,1617,585,1632,1632,1572,...,1584,653,924,924,924,458,905,464,435,1632
Middle East,1497,1497,1497,1481,1451,1430,290,1497,1497,1487,...,1477,930,1176,1176,1176,139,972,135,121,1497
North of Sahara,1104,1104,1104,1049,1074,1061,336,1104,1104,1087,...,1086,834,754,754,754,58,639,60,57,1104
Oceania,42,42,42,40,36,42,16,42,42,42,...,42,32,42,42,42,16,41,16,16,42
Polynesia,14,14,14,14,12,14,11,14,14,6,...,14,5,6,6,6,4,6,4,4,14
South & Central Asia,17668,17668,17668,17576,16345,8256,4102,17668,17668,8277,...,15952,4389,6415,6415,6415,3354,6015,3388,3011,17668
South America,4925,4925,4925,4862,4819,4890,1516,4925,4925,4540,...,4675,2736,3231,3230,3230,227,2829,236,223,4925
South of Sahara,1944,1944,1944,1908,1522,1944,1500,1944,1944,1944,...,1928,1055,1890,1889,1888,1446,1819,1444,1304,1944
Southern Africa,2758,2758,2758,2715,2514,2743,1135,2758,2758,2539,...,2688,1701,2181,2181,2181,677,2024,736,657,2758
Western Africa,6816,6816,6816,6657,5881,6752,3365,6816,6816,6689,...,6733,3844,6048,6048,6048,2815,5860,2835,2583,6816

In [10]:
df.groupby('country').count()

,year,organization_name,region,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,financial_instrument,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,192,192,192,190,26,29,92,192,192,181,...,190,140,158,158,158,71,119,71,68,192
"Africa, regional",2576,2576,2576,2538,2280,2554,1060,2576,2576,2576,...,2565,1884,2472,2469,2473,956,2044,956,880,2576
Albania,37,37,37,37,37,37,5,37,37,32,...,33,16,28,28,28,0,27,2,0,37
Algeria,12,12,12,12,11,12,1,12,12,12,...,12,11,12,12,12,0,10,0,0,12
"America, regional",1007,1007,1007,1003,997,1007,33,1007,1007,1007,...,1007,968,1006,1006,1006,33,419,32,31,1007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza Strip,89,89,89,88,85,88,8,89,89,89,...,85,76,80,80,80,7,28,6,6,89
"Western Africa, regional",314,314,314,299,309,309,5,314,314,314,...,314,187,314,314,314,5,304,5,5,314
Yemen,39,39,39,38,37,38,14,39,39,39,...,39,26,32,32,32,8,24,8,8,39
Zambia,546,546,546,538,461,546,259,546,546,536,...,545,353,511,511,511,239,504,246,226,546
Zimbabwe,381,381,381,377,336,381,137,381,381,362,...,371,270,341,341,341,114,333,148,113,381

In [11]:
df.groupby('grant_recipient_project_title').count()

,year,organization_name,region,country,usd_disbursements_defl,project_description,expected_duration,type_of_flow,Donor_country,financial_instrument,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
grant_recipient_project_title,,,,,,,,,,,,,,,,,,,,,
"""+1 Plan"" Rural Kindergarten Public Welfare Project",2,2,2,2,2,2,0,2,2,0,...,2,0,0,0,0,0,0,0,0,2
"""+1 Plan"" Rural Kindergarten Public Welfare Project (Phase 3)",1,1,1,1,1,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
"""+1 Plan"" Rural Kindergarten Public Welfare Project (Phase 4)",1,1,1,1,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,1
"""1 Breakfast"" Charity Project",2,2,2,2,2,2,0,2,2,0,...,2,0,0,0,0,0,0,0,0,2
"""1+1"" China Legal Aid Volunteer Action Project",1,1,1,1,1,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
【Only Love Mom】,1,1,1,1,1,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
【Other projects】,2,2,2,2,2,2,0,2,2,0,...,2,0,0,0,0,0,0,0,0,2
【Other public welfare projects】,1,1,1,1,1,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
【Rural Revitalization Project】,3,3,3,3,3,3,0,3,3,0,...,3,0,0,0,0,0,0,0,0,3
【Rural Revitalization】,1,1,1,1,1,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1

### Check for null columns

In [12]:
df.head()

,year,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
0,2021,Lund Trust,South & Central Asia,Afghanistan,0.007338,For Afghanistan,To support Turquoise Mountain's work in Afghan...,NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia
1,2021,Lund Trust,Eastern Africa,Kenya,0.008166,Vanga Blue Forest,Towards mangrove conservation in southern Kenya,NaN,Cross-border,United Kingdom,...,General Environment Protection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa
2,2022,Lund Trust,Europe,Ukraine,6.795787,"To the crisis appeal, to support the people of...","To the crisis appeal, to support the people of...",NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
3,2022,Lund Trust,Europe,Ukraine,0.339789,Match funding for the Refugee Council's appeal,"To develop, expand and run the services needed...",NaN,Cross-border,United Kingdom,...,Refugees in Donor Countries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
4,2022,Lund Trust,Europe,Ukraine,4.077472,To support the emergency response in Ukraine.,To support the emergency response in Ukraine.,NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe

In [13]:
df.groupby('expected_duration', dropna=False).count()

,year,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,type_of_flow,Donor_country,financial_instrument,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
expected_duration,,,,,,,,,,,,,,,,,,,,,
2004 - 2021,1,1,1,1,1,1,1,1,1,0,...,1,0,0,0,0,0,0,0,0,1
2005 - 2021,2,2,2,2,2,2,2,2,2,0,...,2,0,0,0,0,0,0,0,0,2
2005 - 2022,5,5,5,5,5,5,5,5,5,0,...,5,0,0,0,0,0,0,0,0,5
2007 - 2021,1,1,1,1,1,1,1,1,1,1,...,1,0,1,1,1,1,1,1,0,1
2007 - 2022,2,2,2,2,2,2,2,2,2,1,...,2,0,1,1,1,1,1,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024 -2025,1,1,1,1,0,1,1,1,1,1,...,1,1,0,0,0,0,0,0,0,1
2024-2027,1,1,1,1,1,1,1,1,1,0,...,1,0,0,0,0,0,0,0,0,1
2025 - 2027,1,1,1,1,0,1,1,1,1,1,...,1,1,0,0,0,0,0,0,0,1
2026 - 2027,1,1,1,1,0,1,1,1,1,1,...,1,1,0,0,0,0,0,0,0,1
NaN,86125,86125,86125,86125,85344,62001,76150,86125,86125,41521,...,82878,31139,37693,37677,37687,84,31162,335,50,86125

In [14]:
df.to_csv("../../data/clean_year_region.csv", index=False)