# View funding by region, country, and year=

In [2]:
import pandas as pd 
import plotly.express as px

df = pd.read_csv("../../data/clean_year_region.csv")
df.head()

/var/folders/sp/zrg_wt6n4hs4l4nz5y1b6zs00000gn/T/ipykernel_51550/2641432959.py:4: DtypeWarning: Columns (0: grant_recipient_project_title, 1: expected_duration, 2: financial_instrument, 3: modality_of_giving, 4: gender_dimension, 5: additional_info, 6: subsector, 7: Sector, 8: channel_name, 9: channel_reported_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/clean_year_region.csv")

,year,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,...,sector_description,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro
0,2021,Lund Trust,South & Central Asia,Afghanistan,0.007338,For Afghanistan,To support Turquoise Mountain's work in Afghan...,NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia
1,2021,Lund Trust,Eastern Africa,Kenya,0.008166,Vanga Blue Forest,Towards mangrove conservation in southern Kenya,NaN,Cross-border,United Kingdom,...,General Environment Protection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa
2,2022,Lund Trust,Europe,Ukraine,6.795787,"To the crisis appeal, to support the people of...","To the crisis appeal, to support the people of...",NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
3,2022,Lund Trust,Europe,Ukraine,0.339789,Match funding for the Refugee Council's appeal,"To develop, expand and run the services needed...",NaN,Cross-border,United Kingdom,...,Refugees in Donor Countries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
4,2022,Lund Trust,Europe,Ukraine,4.077472,To support the emergency response in Ukraine.,To support the emergency response in Ukraine.,NaN,Cross-border,United Kingdom,...,Emergency Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe

In [9]:
df[["country", "usd_disbursements_defl"]][df["country"].isin(["India", "Ukraine", "Afghanistan", "Kenya"])].groupby("country").sum()

             usd_disbursements_defl
country
Afghanistan              167.312462
India                   6174.581735
Kenya                   1617.995267
Ukraine                  663.058907

In [10]:
test = df[["country", "usd_disbursements_defl"]][df["country"].isin(["India", "Ukraine", "Afghanistan", "Kenya"])].groupby("country", as_index=False).sum()
fig = px.choropleth(
    test,
    locations="country",
    locationmode="country names",
    color="usd_disbursements_defl"
)

fig.show()

/var/folders/sp/zrg_wt6n4hs4l4nz5y1b6zs00000gn/T/ipykernel_51550/4152236069.py:2: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(