In [5]:
import pandas as pd 

df = pd.read_csv("../../backend/data/dropped_rows.csv")
df["sdg_focus"] = df["sdg_focus"].astype(str).str.strip()
df["region"] = df["region"].astype(str).str.strip()

df.head()

/var/folders/sp/zrg_wt6n4hs4l4nz5y1b6zs00000gn/T/ipykernel_56760/2744818498.py:3: DtypeWarning: Columns (0: grant_recipient_project_title) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../backend/data/dropped_rows.csv")

,year,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,Donor_country,sdg_focus,mission_desc
0,2022,True Colours Trust,Eastern Africa,Malawi,0.041862,Towards the costs of updating lockable cupboar...,United Kingdom,3.4,"Achieve By 2030, reduce by one third premature..."
1,2020,True Colours Trust,Eastern Africa,Malawi,0.054969,Towards the purchase of PPE during the COVID19...,United Kingdom,3.3,"Achieve By 2030, end the epidemics of AIDS, tu..."
2,2021,True Colours Trust,Eastern Africa,Malawi,0.366887,Towards Phase 5 of integrating palliative care...,United Kingdom,3.8,"Achieve Achieve universal health coverage, inc..."
3,2021,True Colours Trust,Eastern Africa,Malawi,0.366887,Towards Phase 5 of integrating palliative care...,United Kingdom,3.8,"Achieve Achieve universal health coverage, inc..."
4,2020,True Colours Trust,Eastern Africa,Malawi,0.016170,Towards the production of films on Palliative ...,United Kingdom,3.4,"Achieve By 2030, reduce by one third premature..."

In [ ]:
sdg = "3.4"
region = "Eastern Africa"

data = df[(df["sdg_focus"] == sdg) & (df["region"] == region)]
total_min = data[["year", "usd_disbursements_defl"]].groupby("year").sum().reset_index()["usd_disbursements_defl"].iloc[0]
total_max = data[["year", "usd_disbursements_defl"]].groupby("year").sum().reset_index()["usd_disbursements_defl"].iloc[-1]
growth = total_max - total_min

np.float64(85.13048310584422)

In [27]:
total_funding = data['usd_disbursements_defl'].sum()
total_funding

np.float64(380.8501553137178)

In [ ]:
num_orgs = len(data["organization_name"].unique())
num_proj = len(data["grant_recipient_project_title"].unique())
num_countries = len(data["country"].unique())

24

In [33]:
url = "https://raw.githubusercontent.com/datasets/country-codes/master/data/country-codes.csv"
countries_df = pd.read_csv(url)
countries_df = countries_df[["CLDR display name", "ISO3166-1-Alpha-3"]]
countries_df.columns = ["Name", "ISO"]
countries_df.head()

              Name  ISO
0      Afghanistan  AFG
1  Kepulauan Aland  ALA
2          Albania  ALB
3          Algeria  DZA
4    Samoa Amerika  ASM

In [ ]:
countries_df[""]

                  Name  ISO
0          Afghanistan  AFG
1      Kepulauan Aland  ALA
2              Albania  ALB
3              Algeria  DZA
4        Samoa Amerika  ASM
..                 ...  ...
244  Wallis dan Futuna  WLF
245       Sahara Barat  ESH
246              Yaman  YEM
247             Zambia  ZMB
248           Zimbabwe  ZWE

[249 rows x 2 columns]